export const FETCH_HOLIDAYS_START = "FETCH_HOLIDAYS_START";
export const FETCH_HOLIDAYS_SUCCESS = "FETCH_HOLIDAYS_SUCCESS";
export const FETCH_HOLIDAYS_FAILED = "FETCH_HOLIDAYS_FAILED";

export const SET_DAYS = "SET_DAYS";
export const SET_HOLIDAYS_START_DATE = "SET_HOLIDAYS_START_DATE";
export const SET_HOLIDAYS_END_DATE = "SET_HOLIDAYS_END_DATE";
